apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugkiller-web
  labels:
    app: bugkiller
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugkiller
      component: web
  template:
    metadata:
      labels:
        app: bugkiller
        component: web
    spec:
      containers:
      - name: web
        image: bugkiller:compose-mysql  # 使用我们之前构建的本地镜像
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_DEBUG
          value: "1"
        - name: DATABASE_TYPE
          value: "mysql"
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "root"
        - name: DB_NAME
          value: "bugkiller"
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        readinessProbe:
          httpGet:
            path: /metrics
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: code-volume
          mountPath: /app
      volumes:
      - name: code-volume
        hostPath:
          path: /d/1-work/python-study/bug_killer_project
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: bugkiller-service
spec:
  type: NodePort
  selector:
    app: bugkiller
    component: web
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001 # 这样我们可以通过 http://localhost:30001 访问
