apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugkiller-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugkiller
      component: worker
  template:
    metadata:
      labels:
        app: bugkiller
        component: worker
    spec:
      containers:
      - name: worker
        image: bugkiller:celery-worker
        imagePullPolicy: IfNotPresent
        command: ["celery", "-A", "tasks.celery_app", "worker", "--loglevel=info"]
        env:
        - name: DATABASE_TYPE
          value: "mysql"
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "root"
        - name: DB_NAME
          value: "bugkiller"
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
